spring:
  rabbitmq:
    addresses: ${vcap.services.${PREFIX:}rabbitmq.credentials.uri:amqp://${RABBITMQ_HOST:172.18.0.3}:${RABBITMQ_PORT:5672}}
   
zuul:
  add-host-header: true
  ignore-security-headers: false
  sensitiveHeaders:
  prefix: /api
  ignored-services: '*'
  routes:
    security-server:
      path: /oauth/**
      serviceId: OAUTH-SERVER
      stripPrefix: false
    ms-hub:
      path: /hub/v1/**
      serviceId: MS-HUB
      stripPrefix: false  
    backoffice-web:
      path: /backoffice-web/v1/**
      serviceId: BACKOFFICE-WEB
      stripPrefix: false
    ms-hub-backoffice:
      path: /hub-backoffice/v1/**
      serviceId: MS-HUB-BACKOFFICE
      stripPrefix: false
    ms-hub-backoffice-liquidacion:
      path: /ms-hub-backoffice-liquidacion/v1/**
      serviceId: MS-HUB-BACKOFFICE-LIQUIDACION
      stripPrefix: false
    ms-hub-backoffice-liquidacion-360get:
      path: /ms-hub-backoffice-liquidacion-360get/v1/**
      serviceId: MS-HUB-BACKOFFICE-LIQUIDACION-360GET
      stripPrefix: false
    ms-hub-backoffice-liquidacion-360:
      path: /ms-hub-backoffice-liquidacion-360/v1/**
      serviceId: MS-HUB-BACKOFFICE-LIQUIDACION-360
      stripPrefix: false
    ms-hub-backoffice-reclamos:
      path: /ms-hub-backoffice-reclamos/v1/**
      serviceId: MS-HUB-BACKOFFICE-RECLAMOS
      stripPrefix: false
    ms-hub-backoffice-transversales:
      path: /ms-hub-backoffice-transversales/v1/**
      serviceId: MS-HUB-BACKOFFICE-TRANSVERSALES
      stripPrefix: false
    ms-hub-backoffice-generales:
      path: /ms-hub-backoffice-generales/v1/**
      serviceId: MS-HUB-BACKOFFICE-GENERALES
      stripPrefix: false
    ms-hub-backoffice-comercio-ordenpago:
      path: /ms-hub-backoffice-comercio-ordenpago/v1/**
      serviceId: MS-HUB-BACKOFFICE-COMERCIO-ORDENPAGO
      stripPrefix: false
    ratelimit:
      enabled: false
      repository: IN_MEMORY
      behind-proxy: true
      default-policy: #optional - will apply unless specific policy exists
        limit: 20 #optional - request number limit per refresh interval window
        quota: 1000 #optional - request time limit per refresh interval window (in seconds)
        refresh-interval: 60 #default value (in seconds)
    
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
  
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 60000
  eureka:
    enabled: true   
  eager-load:
    enabled: false
    
security:
  basic:
    enabled: false
  user:
    name: zuul
    password: a39WqtRWAaXhckj
    role: ADMIN

logging:  
#  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud.netflix.zuul: 'DEBUG'
    org.springframework.cloud.netflix.ribbon: 'DEBUG'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'
