spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.40.4.79:5432/hub-desarrollo
    username: hub-none
    password: Apimono123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        default_schema: hub
        enable_lazy_load_no_trans: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hub      

server.port: ${PORT:}
server:
  servlet:
    context-path: /ms-hub-backoffice-comercio-consultapago/v1

management:
  security:
    sessions: stateless
    enabled: false
  context-path: /admin
  port: ${PORT_ADMIN:}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
    
logging:
  level:
    org.springframework.boot: 'INFO'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'

config:
  host: http://172.18.0.4/api/
  uri_token_hub: http://172.18.0.4/api/oauth/token
  host_sifco: http://172.18.0.56:80/

security:
  sessions: stateless
  basic:
    enabled: false
  user:
    password: none    
  oauth2:
    resource:
      jwt:
        keyValue: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo1jWPfjvJxaXCHzvClU7
            uJg+6AlZ8ht1Rbr+7Wo5o+YBWgCc6lZmSv/mwxvfL/wqagQ/W756a8vUJ7qFz/k9
            eBSJQSRuzJ6pT4OMMR9gbmYroh3RM/Xd5RelJgT3+OrvjAZr1pFYdAwp0q1T9XPa
            6PnCXq8KhIqNPxMjcaBrOycWEgWE4g4VnnrKDLtMmEZZIc0EMv8j7womsyNkbTyl
            nPsbFttNwtFoTVJeqvD01Fd6ISaoOVQAUfAcxvp77B/A1g0No3GHBupEtW3Hgp2/
            80Zl0+Gwjl6Wag5Mu9H7MIUPo+4xFGAJ0uwseHiErZqdWlHIo179IacB87+9Vt0g
            pwIDAQAB
            -----END PUBLIC KEY-----
eureka:
  instance:
    metadata-map:
      management:
        port: 9090
